import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Component/Navbar";
import Footer from "./Component/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

<<<<<<< HEAD
        <Navbar />
        {children}
        <Footer />
=======

        {children}

>>>>>>> 41514c4190f7b76c51a19131a467d473eb9f779d

      </body>
    </html>
  );
}
